services:
  app:
    container_name: "characreate"
    build: .
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=characreate.bedlinger.at
      - LETSENCRYPT_HOST=characreate.bedlinger.at
      - VIRTUAL_PORT=3000
      - API_URL=${API_URL}
      - API_KEY=${API_KEY}
    volumes:
      - characreate_data:/app/.data
    restart: unless-stopped
    networks:
      - "web"

volumes:
  characreate_data:

networks:
  web:
    external: true
